### ISSUE TITLE
Cypress test is failing

### ISSUE THREAD

**Issue by hip3r** [poslovnimediji/decap-cms#2]
I cloned latest master version and ran cypress e2e tests.
Most of tests failed, because content creation is not successfull
![image](https://github.com/poslovnimediji/decap-cms/assets/10455862/66120efa-e21c-4612-981f-884cbda94677)
![image](https://github.com/poslovnimediji/decap-cms/assets/10455862/d50d95e7-8f52-4dbc-bd22-118c8cd5b22b)

If I try to recreate issue manually, I get stopped by text editor, which detects empty value 
![image](https://github.com/poslovnimediji/decap-cms/assets/10455862/d7588495-4f56-4089-8844-ada57347d66f)

check if you get the same errors on your machine

**Comment by demshy** [comment]
is this fixed now after https://github.com/decaporg/decap-cms/pull/7126 ?

**Comment by hip3r** [comment]
in general it's solved, but there are still 3 tests failing. Do you get the same result on Mac?
![image](https://github.com/poslovnimediji/decap-cms/assets/10455862/43eb0192-e4c2-4009-9d5e-21266c32b065)


Proxy Backend Simple Workflow - 'git' mode -- successfully loads -- after each hook (failed)
![image](https://github.com/poslovnimediji/decap-cms/assets/10455862/3b79297c-03e0-4666-9245-0e2bd484b983)
Proxy Backend Media Library - 'git' mode -- should show published entry image in grid view -- after all hook (failed)
![Proxy Backend Media Library - 'git' mode -- should show published entry image in grid view -- after all hook (failed)](https://github.com/poslovnimediji/decap-cms/assets/10455862/f0541d99-147f-44a3-a889-09aaf2b9a182)
Proxy Backend Media Library - 'git' mode -- can save entry with image -- after each hook (failed)
![Proxy Backend Media Library - 'git' mode -- can save entry with image -- after each hook (failed)](https://github.com/poslovnimediji/decap-cms/assets/10455862/1a1c71d6-88d9-46f7-822f-a10b8283010e)
